import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { Menu, MainCard, WorkExp, Edu, AboutMe, Tech } from '../components'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-me-secondary min-h-screen'>
        <MainCard />
        {/* <div className='invisible sticky top-0 visible'>
          <Menu />
        </div> */}
        <Tech />
        <WorkExp />
        <Edu />
        <AboutMe />
      </main>

    </div>
  )
}
