import Head from 'next/head'
import { MainCard, WorkExp, Edu, AboutMe, Tech, ContactMe, Modal } from '../components'
import { useEffect, useState } from 'react'
import { getEgg, setEgg } from '../helpers/egg'


export default function Home() {
  const [easterEgg, setEasterEgg] = useState()

  useEffect(() => {
    let egg = getEgg()
    if (!egg) {
      console.log('resetting');
      resetEgg()
    } else {
      setEasterEgg(egg)
    }
  }, [])

  useEffect(() => {
    setEgg(easterEgg)
  }, [easterEgg])

  const resetEgg = () => {
    localStorage.clear()
    let egg = {
      showingPicture: 'visible',
      showingHint: 'hidden',
      Zindex: '-z-10',
      sheild: 'bg-blue-500 rounded-full p-1',
      eggClick: false
    }
    setEasterEgg(egg)
    console.log("finished resetting");
  }

  const changeEggState = (obj) => {
    setEasterEgg({
      ...easterEgg,
      ...obj
    })
  }

  return (
    <div>
      <Head>
        <title>Tyler Thibault</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href='img/thinkingMe.jpg' />
      </Head>

      <main className='bg-me-secondary min-h-screen pb-8'>
        {
          easterEgg ?
            <>
              {
                easterEgg.showHint &&
                <Modal
                  content={easterEgg.currentHint}
                  title="The Egg Hunt"
                  onClose={() => changeEggState({
                    showHint: false
                  })}
                />
              }
              {
                easterEgg.eggHunt &&
                <>
                  <div className='bg-me-primary fixed top-2 left-2 p-5 z-20 rounded-lg shadow-md shadow-black'>
                    <button className='p-3 bg-me-accent rounded-lg shadow-md shadow-black' onClick={() => changeEggState({
                      showHint: true
                    })}>Current Hint</button>
                  </div>
                  <div className='bg-me-primary p-5 fixed top-2 right-3 rounded-lg shadow-lg shadow-black text-white z-20'>
                    <div className=' cursor-pointer bg-me-secondary p-3 rounded-lg shadow shadow-black'>
                      <span onClick={() => resetEgg()}>Reset</span>
                    </div>
                  </div>
                </>
              }
              <MainCard
                egg={easterEgg}
                resetEgg={() => resetEgg()}
                changeEggState={(obj) => changeEggState(obj)}
              />
              <Tech
                egg={easterEgg}
                changeEggState={(obj) => changeEggState(obj)}
              />
              <WorkExp
                egg={easterEgg}
                changeEggState={(obj) => changeEggState(obj)}
              />
              <Edu
                egg={easterEgg}
                changeEggState={(obj) => changeEggState(obj)}
              />
              <AboutMe />
              <ContactMe />
            </>
            :
            'Loading'
        }
      </main>

    </div>
  )
}
