import Head from 'next/head'
import { MainCard, WorkExp, Edu, AboutMe, Tech, ContactMe, Modal } from '../components'
import { useEffect, useState } from 'react'
import { getEgg, setEgg } from '../helpers/egg'


export default function Home() {
  const [easterEgg, setEasterEgg] = useState()

  useEffect(() => {
    let egg = getEgg()
    if (!egg) {
      console.log('resetting');
      resetEgg()
    } else {
      setEasterEgg(egg)
    }
  }, [])

  useEffect(() => {
    console.log(easterEgg);
    setEgg(easterEgg)
  }, [easterEgg])

  const resetEgg = () => {
    let egg = {
      showingPicture: 'visible',
      showingHint: 'hidden',
      Zindex: '-z-10',
      sheild: 'bg-blue-500 rounded-full p-1',
      eggClick: false
    }
    setEasterEgg(egg)
    console.log("finished resetting");
  }

  const changeEggState = (obj) => {
    setEasterEgg({
      ...easterEgg,
      ...obj
    })
  }

  return (
    <div>
      <Head>
        <title>Tyler Thibault</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href='img/thinkingMe.jpg' />
      </Head>

      <main className='bg-me-secondary min-h-screen pb-8'>
        {
          easterEgg ?
            <>
              {
                easterEgg.showHint &&
                <Modal
                  content={easterEgg.currentHint}
                  onClose={() => changeEggState({
                    showHint: false
                  })}
                />
              }
              {
                easterEgg.eggHunt &&
                <div>
                  <button className='p-3 bg-me-accent rounded-lg fixed top-5 left-5' onClick={() => changeEggState({
                    showHint: true
                  })}>Current Hint</button>
                </div>
              }
              <MainCard
                egg={easterEgg}
                resetEgg={() => resetEgg()}
                changeEggState={(obj) => changeEggState(obj)}
              />
              <Tech />
              <WorkExp
                egg={easterEgg}
                changeEggState={(obj) => changeEggState(obj)}
              />
              <Edu
                egg={easterEgg}
                changeEggState={(obj) => changeEggState(obj)}
              />
              <AboutMe />
              <ContactMe />
            </>
            :
            'Loading'
        }
      </main>

    </div>
  )
}
